version: '3.9'

services:
  mongodb:
    image: mongo:latest
    env_file:
      - ./server/.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  server:
    build: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - 3000:3000
    command: yarn start:dev
    env_file:
      - ./server/.env
    depends_on:
      - mongodb

volumes:
  mongodb_data: